# Generated by Django 4.2.21 on 2026-01-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UacAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uac_key', models.CharField(default='uac_1', max_length=5, unique=True)),
                ('uac_config_name', models.CharField(default='Default UAC', max_length=28, unique=True)),
                ('select_uac', models.CharField(default='uac_basic.xml', max_length=100)),
                ('uac_remote', models.GenericIPAddressField(default='10.0.0.10')),
                ('uac_remote_port', models.PositiveIntegerField(default=5060)),
                ('uac_local', models.GenericIPAddressField(default='10.0.0.5')),
                ('uac_local_port', models.PositiveIntegerField(default=5060)),
                ('uac_protocol', models.CharField(choices=[('un', 'UDP'), ('tn', 'TCP')], default='un', max_length=10)),
                ('called_party', models.CharField(blank=True, max_length=50)),
                ('calling_party', models.CharField(blank=True, max_length=50)),
                ('total_no_of_calls', models.PositiveIntegerField(default=1)),
                ('cps', models.PositiveIntegerField(default=1)),
                ('max_ccl', models.PositiveIntegerField(default=1)),
                ('min_rtp_port', models.PositiveIntegerField(default=10000)),
                ('max_rtp_port', models.PositiveIntegerField(default=20000)),
                ('stun_server', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active_config', models.BooleanField(default=False)),
                ('csv_inf', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UasAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uas_key', models.CharField(default='uas_1', max_length=5, unique=True)),
                ('uas_config_name', models.CharField(default='Default UAS', max_length=28, unique=True)),
                ('select_uas', models.CharField(default='uas_basic.xml', max_length=100)),
                ('uas_remote', models.GenericIPAddressField(default='10.0.0.20')),
                ('uas_remote_port', models.PositiveIntegerField(default=5060)),
                ('uas_local', models.GenericIPAddressField(default='10.0.0.5')),
                ('uas_local_port', models.PositiveIntegerField(default=5060)),
                ('uas_protocol', models.CharField(choices=[('un', 'UDP'), ('tn', 'TCP')], default='un', max_length=10)),
                ('cps', models.PositiveIntegerField(default=1)),
                ('max_ccl', models.PositiveIntegerField(default=1)),
                ('min_rtp_port', models.PositiveIntegerField(default=10000)),
                ('max_rtp_port', models.PositiveIntegerField(default=20000)),
                ('is_active_config', models.BooleanField(default=False)),
                ('csv_inf', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
